import { afterAll, expect, test } from 'bun:test';
import { z } from 'zod';
import { bulkLoad } from '../../src/core/bulk.ts';
import { defineGraphSchema } from '../../src/core/define-graph-schema.ts';
import { type DbClient, dialectOf } from '../../src/core/dialect.ts';
import { Graph } from '../../src/core/graph.ts';
import { FOREVER } from '../../src/core/runtime.ts';
import { init, readSchemaVersion, SCHEMA_VERSION } from '../../src/core/schema.ts';
import { OverlapError, repairOverlaps } from '../../src/core/upgrade.ts';
import { indexBackedConstraints, makeTestDb } from './harness.ts';

// Schema v2 (docs/bitemporal.md §3): recorded time on both version tables, one live row per id
// held by the database, and the v1 → v2 upgrade that `init` runs on an existing namespace.

const SCHEMA = defineGraphSchema({
	nodes: { person: z.object({ name: z.string(), email: z.string().optional() }) },
	edges: { knows: { from: 'person', to: 'person' } },
});

const teardowns: Array<() => Promise<void>> = [];
afterAll(async () => {
	for (const teardown of teardowns) await teardown();
});

function fresh(): DbClient {
	// file-backed: Graph.updateNode runs a transaction, which detaches a :memory: libSQL client
	const { client, teardown } = makeTestDb({ file: true });
	teardowns.push(teardown);
	return client;
}

/**
 * A namespace exactly as graphx v1 laid it out: no recorded-time columns, rowid version tables
 * on SQLite, `*_asof` indexes, views over `valid_to` alone, stamped `schema_version = 1`.
 * Only the tables the upgrade touches; `init` creates the rest, as it would for a v1 namespace
 * missing a later-added table.
 */
async function v1Namespace(client: DbClient): Promise<void> {
	const d = dialectOf(client);
	const big = d === 'libsql' || d === 'sqlite' ? 'INTEGER' : 'BIGINT';
	const ver =
		d === 'postgres'
			? 'ver bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
			: d === 'duckdb'
				? "ver BIGINT PRIMARY KEY DEFAULT nextval('seq_ver')"
				: 'ver INTEGER PRIMARY KEY';
	const tsv =
		d === 'postgres'
			? ", body_tsv tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED"
			: '';
	const fk = (t: string) => (d === 'duckdb' ? '' : ` REFERENCES ${t}(id)`);
	const stmts = [
		...(d === 'duckdb' ? ['CREATE SEQUENCE IF NOT EXISTS seq_ver START 1'] : []),
		'CREATE TABLE node_identity (id TEXT PRIMARY KEY)',
		'CREATE TABLE edge_identity (id TEXT PRIMARY KEY)',
		'CREATE TABLE graph_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)',
		`CREATE TABLE node_versions (${ver}, id TEXT NOT NULL${fk('node_identity')}, type TEXT NOT NULL,
		  body TEXT, uri TEXT, content_hash TEXT, content_type TEXT, data TEXT NOT NULL DEFAULT '{}',
		  valid_from ${big} NOT NULL, valid_to ${big} NOT NULL DEFAULT ${FOREVER}${tsv})`,
		'CREATE INDEX nv_asof ON node_versions(id, valid_from, valid_to)',
		`CREATE TABLE edge_versions (${ver}, id TEXT NOT NULL${fk('edge_identity')},
		  src TEXT NOT NULL${fk('node_identity')}, dst TEXT NOT NULL${fk('node_identity')}, rel TEXT NOT NULL,
		  weight REAL NOT NULL DEFAULT 1.0, data TEXT NOT NULL DEFAULT '{}', source TEXT,
		  valid_from ${big} NOT NULL, valid_to ${big} NOT NULL DEFAULT ${FOREVER})`,
		'CREATE INDEX ev_src_asof ON edge_versions(src, valid_from, valid_to)',
		'CREATE INDEX ev_dst_asof ON edge_versions(dst, valid_from, valid_to)',
		`CREATE VIEW nodes AS SELECT id, type, body, uri, content_hash, content_type, data
		  FROM node_versions WHERE valid_to = ${FOREVER}`,
		`CREATE VIEW edges AS SELECT id, src, dst, rel, weight, data, source
		  FROM edge_versions WHERE valid_to = ${FOREVER}`,
		"INSERT INTO graph_meta (key, value) VALUES ('schema_version', '1')",
	];
	for (const sql of stmts) await client.execute(sql);
}

/** Raw v1 rows: a person with one closed and one open version, a second person, an edge. */
async function v1Rows(client: DbClient): Promise<void> {
	const exec = (sql: string, args: unknown[]) => client.execute({ sql, args: args as never[] });
	for (const id of ['A', 'B']) await exec('INSERT INTO node_identity (id) VALUES (?)', [id]);
	await exec(
		'INSERT INTO node_versions (id, type, data, valid_from, valid_to) VALUES (?, ?, ?, ?, ?)',
		['A', 'person', '{"name":"a1"}', 1000, 2000],
	);
	await exec('INSERT INTO node_versions (id, type, data, valid_from) VALUES (?, ?, ?, ?)', [
		'A',
		'person',
		'{"name":"a2"}',
		2000,
	]);
	await exec('INSERT INTO node_versions (id, type, data, valid_from) VALUES (?, ?, ?, ?)', [
		'B',
		'person',
		'{"name":"b"}',
		1500,
	]);
	await exec('INSERT INTO edge_identity (id) VALUES (?)', ['E']);
	await exec('INSERT INTO edge_versions (id, src, dst, rel, valid_from) VALUES (?, ?, ?, ?, ?)', [
		'E',
		'A',
		'B',
		'knows',
		2500,
	]);
}

test('a v1 namespace upgrades to v2 and every read keeps its answer', async () => {
	const client = fresh();
	await v1Namespace(client);
	await v1Rows(client);

	await init(client);
	expect(await readSchemaVersion(client)).toBe(SCHEMA_VERSION);

	const g = new Graph(client, SCHEMA);
	expect((await g.getNode('A'))?.data).toEqual({ name: 'a2' });
	expect((await g.getNode('A', { asOf: 1500 }))?.data).toEqual({ name: 'a1' });
	expect(await g.getNode('B', { asOf: 1200 })).toBeNull();
	expect((await g.neighbors('A', 'knows')).map((n) => n.id)).toEqual(['B']);

	// recorded time is backfilled from valid time; every row stays a current belief
	const rows = await client.execute(
		'SELECT valid_from, recorded_from, recorded_to FROM node_versions ORDER BY ver',
	);
	for (const r of rows.rows) {
		expect(Number(r.recorded_from)).toBe(Number(r.valid_from));
		expect(Number(r.recorded_to)).toBe(FOREVER);
	}

	// SQLite rebuilt the version tables so a purged ver is never handed out again
	if (dialectOf(client) === 'libsql' || dialectOf(client) === 'sqlite') {
		const defs = await client.execute(
			"SELECT sql FROM sqlite_master WHERE type = 'table' AND name IN ('node_versions', 'edge_versions')",
		);
		expect(defs.rows.map((r) => /AUTOINCREMENT/.test(String(r.sql)))).toEqual([true, true]);
	}

	// the upgraded namespace takes writes, and a re-init is a no-op
	await g.updateNode('B', { data: { name: 'b2' } });
	await init(client);
	expect((await g.getNode('B'))?.data).toEqual({ name: 'b2' });
	expect((await g.getNode('A', { asOf: 1500 }))?.data).toEqual({ name: 'a1' });
});

test('a v1 namespace with two open versions of one id refuses to upgrade until repaired', async () => {
	const client = fresh();
	await v1Namespace(client);
	await v1Rows(client);
	// the phase-0 bulkLoad bug: a second open version of A
	await client.execute({
		sql: 'INSERT INTO node_versions (id, type, data, valid_from) VALUES (?, ?, ?, ?)',
		args: ['A', 'person', '{"name":"a-stale-reload"}', 2000],
	});

	const err = await init(client).catch((e: unknown) => e);
	expect(err).toBeInstanceOf(OverlapError);
	expect((err as OverlapError).nodes).toEqual(['A']);
	expect(await readSchemaVersion(client)).toBe(1);

	// keeps the version written last, takes the other out of current belief, deletes nothing
	expect(await repairOverlaps(client)).toEqual({ nodes: 1, edges: 0 });
	await init(client);
	expect(await readSchemaVersion(client)).toBe(SCHEMA_VERSION);
	const g = new Graph(client, SCHEMA);
	expect((await g.getNode('A'))?.data).toEqual({ name: 'a-stale-reload' });
	const all = await client.execute({
		sql: 'SELECT COUNT(*) AS n FROM node_versions WHERE id = ?',
		args: ['A'],
	});
	expect(Number(all.rows[0]!.n)).toBe(3);
});

indexBackedConstraints('a declared unique prop survives the upgrade and still holds', async () => {
	const client = fresh();
	await v1Namespace(client);
	await v1Rows(client);
	// a v1 constraint index, predicate on valid_to alone
	if (dialectOf(client) === 'postgres') {
		await client.execute(
			`CREATE UNIQUE INDEX ux_6_person_email ON node_versions ((data::jsonb ->> 'email')) WHERE valid_to = ${FOREVER} AND type = 'person'`,
		);
	} else {
		await client.execute(
			"ALTER TABLE node_versions ADD COLUMN gp_email TEXT GENERATED ALWAYS AS (json_extract(data, '$.email')) VIRTUAL",
		);
		await client.execute(
			`CREATE UNIQUE INDEX ux_6_person_email ON node_versions(gp_email) WHERE valid_to = ${FOREVER} AND type = 'person'`,
		);
	}

	await init(client);
	const g = new Graph(client, SCHEMA);
	await g.addNode({ type: 'person', data: { name: 'c', email: 'x@example.com' } });
	await expect(
		g.addNode({ type: 'person', data: { name: 'd', email: 'x@example.com' } }),
	).rejects.toThrow();
});

indexBackedConstraints('the database refuses a second live row for one id', async () => {
	const client = fresh();
	await init(client);
	const g = new Graph(client, SCHEMA);
	const a = await g.addNode({ type: 'person', data: { name: 'a' } });
	await expect(
		client.execute({
			sql: 'INSERT INTO node_versions (id, type, data, valid_from) VALUES (?, ?, ?, ?)',
			args: [a.id, 'person', '{"name":"raw"}', 5],
		}),
	).rejects.toThrow();
});

test('live writes are recorded when they take effect; bulk loads when they are loaded', async () => {
	const client = fresh();
	await init(client);
	const g = new Graph(client, SCHEMA);
	const live = await g.addNode({ type: 'person', data: { name: 'live' } });
	const before = Date.now();
	const { ids } = await bulkLoad(client, SCHEMA, [
		{ id: 'OLD', type: 'person', data: { name: 'from 1992' }, validFrom: Date.UTC(1992, 0, 1) },
	]);
	const row = async (id: string) =>
		(
			await client.execute({
				sql: 'SELECT valid_from, recorded_from FROM node_versions WHERE id = ?',
				args: [id],
			})
		).rows[0]!;
	const l = await row(live.id);
	expect(Number(l.recorded_from)).toBe(Number(l.valid_from));
	const b = await row(ids[0]!);
	expect(Number(b.valid_from)).toBe(Date.UTC(1992, 0, 1));
	expect(Number(b.recorded_from)).toBeGreaterThanOrEqual(before);
});
