import type { Dialect } from './dialect.ts';

/**
 * Per-dialect SQL fragments. This is the home for every SQL string that genuinely
 * differs between backends. Each fragment currently implements the **libSQL** form
 * only; the Postgres branch throws until the Postgres adapter lands (it is never
 * reached while the only backend is libSQL). Later phases fill the Postgres branches
 * here instead of rewriting the call sites in schema.ts/constraints.ts/etc.
 *
 * Keep the libSQL output byte-identical to the original inline SQL — the existing test
 * suite asserts behavior against these exact strings.
 */

/** FOREVER sentinel (max JS Date ms) inlined into partial-index / view predicates. */
const FOREVER_LIT = '8640000000000000';

/**
 * Scalar 2-argument max. libSQL overloads `MAX(a, b)` as a scalar; Postgres `max` is
 * strictly an aggregate, so the scalar form is `GREATEST(a, b)`.
 */
export function scalarMax(dialect: Dialect, a: string, b: string): string {
	return dialect === 'postgres' ? `GREATEST(${a}, ${b})` : `MAX(${a}, ${b})`;
}

/**
 * Extract a top-level JSON string field from a `data` column. libSQL applies `->>` to
 * a TEXT JSON column directly; Postgres `->>` needs a `jsonb` operand, so the `text`
 * column is cast first. Returns the field as text in both.
 */
export function jsonField(dialect: Dialect, col: string, key: string): string {
	return dialect === 'postgres' ? `(${col})::jsonb ->> '${key}'` : `${col} ->> '${key}'`;
}

/**
 * The integer type name for a `CAST(... AS …)` of an epoch-ms value. libSQL `INTEGER` is
 * 64-bit; Postgres `INTEGER` is 32-bit and overflows on millisecond timestamps, so it
 * must be `BIGINT`.
 */
export function epochIntType(dialect: Dialect): string {
	return dialect === 'postgres' ? 'BIGINT' : 'INTEGER';
}

/**
 * Prop-equality predicate `<prop> = ?` for a `.where(alias, key, value)` filter. libSQL
 * uses `json_extract(col,'$.key')` (preserves the JSON scalar's type); Postgres extracts
 * as text via `(col)::jsonb ->> 'key'`, so the caller must bind the value as a string for
 * Postgres (text comparison) — see {@link jsonEqArg}.
 */
export function jsonEqExpr(dialect: Dialect, col: string, key: string): string {
	return dialect === 'postgres'
		? `(${col})::jsonb ->> '${key}' = ?`
		: `json_extract(${col}, '$.${key}') = ?`;
}

/** The bound value for a {@link jsonEqExpr} filter — text on Postgres (the `->>` is text). */
export function jsonEqArg(dialect: Dialect, value: unknown): unknown {
	if (dialect !== 'postgres') return value;
	if (value === null || value === undefined) return value;
	return typeof value === 'string' ? value : String(value);
}

/**
 * "One row per key tuple" SELECT for keyset pagination. libSQL relies on `GROUP BY <keys>`
 * with bare non-aggregated columns (SQLite picks one row per group); Postgres forbids that,
 * so it uses `SELECT DISTINCT ON (<keys>)` (the matching `ORDER BY <keys>` is supplied by the
 * caller, which both dialects already emit). Returns the SELECT clause + the trailing GROUP BY
 * (empty on Postgres) to splice around the caller's FROM/WHERE.
 */
export function distinctSelect(
	dialect: Dialect,
	keys: string,
	cols: string,
): { select: string; group: string } {
	return dialect === 'postgres'
		? { select: `SELECT DISTINCT ON (${keys}) ${cols}`, group: '' }
		: { select: `SELECT ${cols}`, group: `GROUP BY ${keys}` };
}

/**
 * Full Postgres DDL, the dialect counterpart to libSQL's {@link import('./schema.ts').schema}.
 * Differences from the libSQL schema, all per the design doc:
 *  - `ver` is `bigint GENERATED ALWAYS AS IDENTITY` (no SQLite rowid alias);
 *  - temporal columns are `bigint` (hold the FOREVER sentinel 8.64e15 comfortably);
 *  - `emb` is pgvector `vector(dim)` (the `vector` extension must exist in `public`,
 *    which is kept on every tenant's search_path);
 *  - full-text is a generated STORED `tsvector` column + GIN index (no FTS5 virtual
 *    table, no sync trigger — the column self-maintains and covers historical rows);
 *  - views use `CREATE OR REPLACE VIEW` (no `IF NOT EXISTS` form in PG);
 *  - `data` stays `text` (callers JSON.stringify/parse exactly as on libSQL).
 * Every `CREATE` is idempotent so it can re-run as a no-op. The partial HNSW vector
 * index ({@link vectorIndexDDL}) is created here too — it accelerates the live-seed ANN
 * scan; the as-of path still over-fetches and temporal-filters (the index is live-only).
 */
export function postgresSchema(dim: number = 768): string {
	return `
CREATE TABLE IF NOT EXISTS node_identity (id text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS edge_identity (id text PRIMARY KEY);

CREATE TABLE IF NOT EXISTS node_versions (
  ver          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id           text NOT NULL REFERENCES node_identity(id),
  type         text NOT NULL,
  body         text,
  uri          text,
  content_hash text,
  embed_hash   text,
  content_type text,
  data        text NOT NULL DEFAULT '{}',
  emb          vector(${dim}),
  valid_from   bigint NOT NULL,
  valid_to     bigint NOT NULL DEFAULT ${FOREVER_LIT},
  body_tsv     tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED
);
CREATE INDEX IF NOT EXISTS nv_asof ON node_versions(id, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS nv_type ON node_versions(type);
CREATE INDEX IF NOT EXISTS nodes_fts_gin ON node_versions USING gin(body_tsv);
${vectorIndexDDL('postgres')}

CREATE TABLE IF NOT EXISTS edge_versions (
  ver        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id         text NOT NULL REFERENCES edge_identity(id),
  src        text NOT NULL REFERENCES node_identity(id),
  dst        text NOT NULL REFERENCES node_identity(id),
  rel        text NOT NULL,
  weight     real NOT NULL DEFAULT 1.0 CHECK (weight >= 0),
  data      text NOT NULL DEFAULT '{}',
  source     text,
  valid_from bigint NOT NULL,
  valid_to   bigint NOT NULL DEFAULT ${FOREVER_LIT}
);
CREATE INDEX IF NOT EXISTS ev_src_asof ON edge_versions(src, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS ev_dst_asof ON edge_versions(dst, valid_from, valid_to);

CREATE OR REPLACE VIEW nodes AS
  SELECT id, type, body, uri, content_hash, embed_hash, content_type, data, emb
  FROM node_versions WHERE valid_to = ${FOREVER_LIT};
CREATE OR REPLACE VIEW edges AS
  SELECT id, src, dst, rel, weight, data, source
  FROM edge_versions WHERE valid_to = ${FOREVER_LIT};

CREATE TABLE IF NOT EXISTS archival_state (
  table_name text PRIMARY KEY, watermark bigint NOT NULL, updated_at bigint NOT NULL
);

-- Eventing (Layer 2): the Postgres counterpart of libSQL's graph_outbox. IDENTITY seq is
-- assigned at INSERT (not commit); outboxTail gates the tail on the snapshot xmin horizon so
-- a lower-seq row from a still-in-flight txn is never skipped (see temporal.ts).
CREATE TABLE IF NOT EXISTS graph_outbox (
  seq    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  op     text NOT NULL,
  entity text NOT NULL,
  id     text NOT NULL,
  label  text,
  src    text,
  dst    text,
  shape  text NOT NULL,
  ts     bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS node_analytics (
  id          text PRIMARY KEY REFERENCES node_identity(id),
  pagerank    real,
  community   bigint,
  degree      bigint,
  computed_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS na_pagerank ON node_analytics(pagerank);
CREATE INDEX IF NOT EXISTS na_community ON node_analytics(community);
CREATE INDEX IF NOT EXISTS na_degree ON node_analytics(degree);
`;
}

function notYet(fragment: string): never {
	throw new Error(
		`dialect-sql: ${fragment}(postgres) not implemented yet — Postgres backend is a later phase`,
	);
}

/** The embedding column's type. libSQL: native `F32_BLOB(dim)`; Postgres: pgvector `vector(dim)`. */
export function embColumnType(dialect: Dialect, dim: number): string {
	if (dialect === 'postgres') notYet('embColumnType');
	return `F32_BLOB(${dim})`;
}

/**
 * Value expression for inserting a FRESH embedding bound as a JSON-array string (`[1,2,3]`).
 * libSQL parses it with `vector(?)`; pgvector casts the same text with `?::vector`.
 */
export function embFreshExpr(dialect: Dialect): string {
	return dialect === 'postgres' ? '?::vector' : 'vector(?)';
}

/**
 * A Postgres `tsquery` that ORs the query's terms. Consumes ONE bound arg: the raw query text.
 *
 * `websearch_to_tsquery` — the obvious choice, and what this used to be — ANDs its terms, while
 * libSQL's {@link sanitizeMatch} joins them with `OR`. Same API, opposite recall: a multi-term
 * query only matched on Postgres if a SINGLE document contained every stem, so the lexical leg
 * usually returned nothing and hybrid retrieval silently degraded to vector-only. Measured on the
 * evaluation corpus before this fix: lexical recall@6 of 0.236 on Postgres against 0.778 on
 * libSQL. The two backends are documented as interchangeable, so `OR` (the higher-recall reading,
 * and the one the fusion step is designed around) is now what both do.
 *
 * Every fragment is a `tsquery` that Postgres itself produced and rendered back to text, so the
 * lexemes are already quoted and escaped — no user input ever reaches `tsquery` syntax, which is
 * what `sanitizeMatch` buys on the libSQL side. Terms the dictionary drops entirely (stopwords)
 * render as `''` and are filtered out; a query of nothing but stopwords aggregates to NULL, and
 * `body_tsv @@ NULL` matches no rows.
 */
function tsQueryOr(): string {
	return `(SELECT NULLIF(string_agg(t.pq, ' | '), '')::tsquery
	FROM (
		SELECT plainto_tsquery('english', tok)::text AS pq
		FROM unnest(string_to_array(?, ' ')) AS tok
	) t
	WHERE t.pq <> '')`;
}

/**
 * Full-text WHERE predicate on a `node_versions` alias. libSQL joins the external-content
 * FTS5 table by rowid (`ver IN (SELECT rowid FROM nodes_fts WHERE nodes_fts MATCH ?)`, bound
 * arg = a sanitized FTS5 expression); Postgres matches the generated `body_tsv` column against
 * {@link tsQueryOr} (bound arg = the RAW query text). Callers gate both on "has usable tokens"
 * before binding.
 */
export function ftsWhere(dialect: Dialect, alias: string): string {
	return dialect === 'postgres'
		? `${alias}.body_tsv @@ ${tsQueryOr()}`
		: `${alias}.ver IN (SELECT rowid FROM nodes_fts WHERE nodes_fts MATCH ?)`;
}

/**
 * Current-time ANN seed sub-SELECT (the body of `seeds AS ( … )`). Consumes 2 bound args:
 * the query embedding (JSON-array string) and k. libSQL uses the partial-live
 * `vector_top_k` index function joined by rowid; pgvector orders live rows by cosine
 * distance (`emb <=> $1::vector`). Both yield the top-k live node ids by ANN rank.
 */
export function annSeedsLive(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `
  SELECT id
  FROM node_versions
  WHERE valid_to = ${FOREVER_LIT} AND emb IS NOT NULL
  ORDER BY emb <=> ?::vector
  LIMIT ?`;
	}
	return `
  SELECT n.id AS id
  FROM vector_top_k('nv_emb_idx', vector(?), ?) v
  JOIN node_versions n ON n.rowid = v.id`;
}

/**
 * As-of-past ANN seed sub-SELECT (the body of `seeds AS ( … )`). Consumes 5 bound args:
 * embedding, over-fetch k, t, t, final k. Over-fetches live ANN candidates, keeps the
 * ids that have a version valid at :t, ranks them, truncates to k. libSQL ranks by the
 * index rowid proxy (`MIN(v.id)`); pgvector ranks by real cosine distance.
 */
export function annSeedsAsOf(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `
  SELECT live.id AS id, live.rk AS rk
  FROM (
    SELECT id, MIN(emb <=> ?::vector) AS rk
    FROM node_versions
    WHERE valid_to = ${FOREVER_LIT} AND emb IS NOT NULL
    GROUP BY id
    ORDER BY rk
    LIMIT ?
  ) live
  WHERE EXISTS (
    SELECT 1 FROM node_versions h
    WHERE h.id = live.id AND h.valid_from <= ? AND ? < h.valid_to
  )
  ORDER BY rk
  LIMIT ?`;
	}
	return `
  SELECT live.id AS id, live.rk AS rk
  FROM (
    SELECT n.id AS id, MIN(v.id) AS rk
    FROM vector_top_k('nv_emb_idx', vector(?), ?) v
    JOIN node_versions n ON n.rowid = v.id
    GROUP BY n.id
  ) live
  WHERE EXISTS (
    SELECT 1 FROM node_versions h
    WHERE h.id = live.id AND h.valid_from <= ? AND ? < h.valid_to
  )
  ORDER BY rk
  LIMIT ?`;
}

/**
 * Standalone live ANN seed list (id only) for hybrid retrieval. Bound args: embedding, k.
 * libSQL: partial-live `vector_top_k`; Postgres: live rows ordered by cosine distance.
 */
export function vecSeedLive(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `SELECT id
FROM node_versions
WHERE valid_to = ${FOREVER_LIT} AND emb IS NOT NULL
ORDER BY emb <=> ?::vector
LIMIT ?`;
	}
	return `SELECT n.id AS id
FROM vector_top_k('nv_emb_idx', vector(?), ?) v
JOIN node_versions n ON n.rowid = v.id
WHERE n.valid_to = ${FOREVER_LIT}`;
}

/**
 * Live full-text seed list (id only, best-first). Bound args: ftsArg, k — where ftsArg is a
 * sanitized FTS5 expression (libSQL) or the raw query text (Postgres). Postgres binds the
 * `tsquery` once via a CTE so the arg count matches libSQL's.
 */
export function ftsSeedLive(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `WITH q AS (SELECT ${tsQueryOr()} AS tq)
SELECT n.id AS id
FROM node_versions n, q
WHERE n.body_tsv @@ q.tq AND n.valid_to = ${FOREVER_LIT}
ORDER BY ts_rank_cd(n.body_tsv, q.tq) DESC
LIMIT ?`;
	}
	return `SELECT n.id AS id
FROM nodes_fts
JOIN node_versions n ON n.ver = nodes_fts.rowid
WHERE nodes_fts MATCH ? AND n.valid_to = ${FOREVER_LIT}
ORDER BY rank
LIMIT ?`;
}

/** As-of full-text seed list. Bound args: ftsArg, t, t, k (Postgres binds tsquery once via CTE). */
export function ftsSeedAsOf(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `WITH q AS (SELECT ${tsQueryOr()} AS tq)
SELECT n.id AS id
FROM node_versions n, q
WHERE n.body_tsv @@ q.tq AND n.valid_from <= ? AND ? < n.valid_to
ORDER BY ts_rank_cd(n.body_tsv, q.tq) DESC
LIMIT ?`;
	}
	return `SELECT n.id AS id
FROM nodes_fts
JOIN node_versions n ON n.ver = nodes_fts.rowid
WHERE nodes_fts MATCH ? AND n.valid_from <= ? AND ? < n.valid_to
ORDER BY rank
LIMIT ?`;
}

/**
 * Build an idempotent INSERT. libSQL uses the `INSERT OR IGNORE` prefix; Postgres appends
 * `ON CONFLICT DO NOTHING`. `values` is the full VALUES clause body, e.g. `(?)` or `(?,?,?)`.
 */
export function insertOrIgnore(
	dialect: Dialect,
	table: string,
	columns: string,
	values: string,
): string {
	return dialect === 'postgres'
		? `INSERT INTO ${table} (${columns}) VALUES ${values} ON CONFLICT DO NOTHING`
		: `INSERT OR IGNORE INTO ${table} (${columns}) VALUES ${values}`;
}

/** Expand a JSON-array string param into a single `id` column of rows. libSQL `json_each`, PG `jsonb_array_elements_text`. */
export function jsonArrayRows(dialect: Dialect): string {
	return dialect === 'postgres'
		? `SELECT jsonb_array_elements_text(?::jsonb) AS id`
		: `SELECT value AS id FROM json_each(?)`;
}

/** Read an embedding back as a JSON-array string. libSQL `vector_extract(emb)`; pgvector's text form IS `[..]`. */
export function embExtract(dialect: Dialect): string {
	return dialect === 'postgres' ? 'emb' : 'vector_extract(emb)';
}

/**
 * Value expression for REBINDING an embedding read back from an existing row (carry-forward
 * on `updateNode`). libSQL rebinds the raw `F32_BLOB` bytes directly (`?`); pgvector reads
 * `emb` back as its text form `[1,2,3]`, so it re-casts with `?::vector`.
 */
export function embRebindExpr(dialect: Dialect): string {
	return dialect === 'postgres' ? '?::vector' : '?';
}

/**
 * The partial live ANN index DDL (D5) — partial over live rows (`valid_to = FOREVER`).
 * libSQL: `libsql_vector_idx` function-expression index. Postgres: a pgvector HNSW
 * index over `emb vector_cosine_ops`, which accelerates the live-seed ANN scan
 * (`ORDER BY emb <=> ?::vector` in {@link annSeedsLive}). The partial predicate matches
 * that query's `valid_to = FOREVER` filter so the planner can use the index; HNSW build
 * params (`m`/`ef_construction`) and `hnsw.ef_search` use pgvector defaults — fine for
 * the test/dev scale, tunable at scale.
 */
export function vectorIndexDDL(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `CREATE INDEX IF NOT EXISTS nv_emb_idx ON node_versions USING hnsw (emb vector_cosine_ops) WHERE valid_to = ${FOREVER_LIT};`;
	}
	return `CREATE INDEX IF NOT EXISTS nv_emb_idx ON node_versions(libsql_vector_idx(emb, 'metric=cosine')) WHERE valid_to = ${FOREVER_LIT};`;
}

/**
 * The full-text index object(s). libSQL: an external-content FTS5 virtual table over
 * `node_versions` (`content_rowid='ver'`). Postgres: a generated `tsvector` column +
 * GIN index (no virtual table), added when the Postgres adapter lands.
 */
export function ftsTableDDL(dialect: Dialect): string {
	if (dialect === 'postgres') notYet('ftsTableDDL');
	return `CREATE VIRTUAL TABLE IF NOT EXISTS nodes_fts USING fts5(body, content='node_versions', content_rowid='ver');`;
}

/**
 * The FTS sync trigger. libSQL external-content FTS5 does NOT auto-sync, so an
 * `AFTER INSERT` trigger mirrors every new `node_versions` row (rowid = `ver`) into
 * `nodes_fts`. Postgres needs no trigger (a generated `tsvector` column self-maintains),
 * so this becomes an empty string there when the adapter lands.
 */
export function ftsTriggerDDL(dialect: Dialect): string {
	if (dialect === 'postgres') notYet('ftsTriggerDDL');
	return `CREATE TRIGGER IF NOT EXISTS nodes_fts_ai AFTER INSERT ON node_versions BEGIN
  INSERT INTO nodes_fts(rowid, body) VALUES (new.ver, new.body);
END;`;
}
