import type { Dialect } from './dialect.ts';

/**
 * Per-dialect SQL fragments. This is the home for every SQL string that genuinely
 * differs between backends. Each fragment currently implements the **libSQL** form
 * only; the Postgres branch throws until the Postgres adapter lands (it is never
 * reached while the only backend is libSQL). Later phases fill the Postgres branches
 * here instead of rewriting the call sites in schema.ts/constraints.ts/etc.
 *
 * Keep the libSQL output byte-identical to the original inline SQL — the existing test
 * suite asserts behavior against these exact strings.
 */

/** FOREVER sentinel (max JS Date ms) inlined into partial-index / view predicates. */
const FOREVER_LIT = '8640000000000000';

/**
 * Scalar 2-argument max. libSQL overloads `MAX(a, b)` as a scalar; Postgres `max` is
 * strictly an aggregate, so the scalar form is `GREATEST(a, b)`.
 */
export function scalarMax(dialect: Dialect, a: string, b: string): string {
	return dialect === 'postgres' ? `GREATEST(${a}, ${b})` : `MAX(${a}, ${b})`;
}

/**
 * Extract a top-level JSON string field from a `props` column. libSQL applies `->>` to
 * a TEXT JSON column directly; Postgres `->>` needs a `jsonb` operand, so the `text`
 * column is cast first. Returns the field as text in both.
 */
export function jsonField(dialect: Dialect, col: string, key: string): string {
	return dialect === 'postgres' ? `(${col})::jsonb ->> '${key}'` : `${col} ->> '${key}'`;
}

/**
 * The integer type name for a `CAST(... AS …)` of an epoch-ms value. libSQL `INTEGER` is
 * 64-bit; Postgres `INTEGER` is 32-bit and overflows on millisecond timestamps, so it
 * must be `BIGINT`.
 */
export function epochIntType(dialect: Dialect): string {
	return dialect === 'postgres' ? 'BIGINT' : 'INTEGER';
}

/**
 * Prop-equality predicate `<prop> = ?` for a `.where(alias, key, value)` filter. libSQL
 * uses `json_extract(col,'$.key')` (preserves the JSON scalar's type); Postgres extracts
 * as text via `(col)::jsonb ->> 'key'`, so the caller must bind the value as a string for
 * Postgres (text comparison) — see {@link jsonEqArg}.
 */
export function jsonEqExpr(dialect: Dialect, col: string, key: string): string {
	return dialect === 'postgres'
		? `(${col})::jsonb ->> '${key}' = ?`
		: `json_extract(${col}, '$.${key}') = ?`;
}

/** The bound value for a {@link jsonEqExpr} filter — text on Postgres (the `->>` is text). */
export function jsonEqArg(dialect: Dialect, value: unknown): unknown {
	if (dialect !== 'postgres') return value;
	if (value === null || value === undefined) return value;
	return typeof value === 'string' ? value : String(value);
}

/**
 * "One row per key tuple" SELECT for keyset pagination. libSQL relies on `GROUP BY <keys>`
 * with bare non-aggregated columns (SQLite picks one row per group); Postgres forbids that,
 * so it uses `SELECT DISTINCT ON (<keys>)` (the matching `ORDER BY <keys>` is supplied by the
 * caller, which both dialects already emit). Returns the SELECT clause + the trailing GROUP BY
 * (empty on Postgres) to splice around the caller's FROM/WHERE.
 */
export function distinctSelect(
	dialect: Dialect,
	keys: string,
	cols: string,
): { select: string; group: string } {
	return dialect === 'postgres'
		? { select: `SELECT DISTINCT ON (${keys}) ${cols}`, group: '' }
		: { select: `SELECT ${cols}`, group: `GROUP BY ${keys}` };
}

/**
 * Full Postgres DDL, the dialect counterpart to libSQL's {@link import('./schema.ts').schema}.
 * Differences from the libSQL schema, all per the design doc:
 *  - `ver` is `bigint GENERATED ALWAYS AS IDENTITY` (no SQLite rowid alias);
 *  - temporal columns are `bigint` (hold the FOREVER sentinel 8.64e15 comfortably);
 *  - `emb` is pgvector `vector(dim)` (the `vector` extension must exist in `public`,
 *    which is kept on every tenant's search_path);
 *  - full-text is a generated STORED `tsvector` column + GIN index (no FTS5 virtual
 *    table, no sync trigger — the column self-maintains and covers historical rows);
 *  - views use `CREATE OR REPLACE VIEW` (no `IF NOT EXISTS` form in PG);
 *  - `props` stays `text` (callers JSON.stringify/parse exactly as on libSQL).
 * Every `CREATE` is idempotent so it can re-run as a no-op. The HNSW vector index is
 * deliberately NOT created here — it is added with the vector-search port (later phase).
 */
export function postgresSchema(dim: number = 768): string {
	return `
CREATE TABLE IF NOT EXISTS node_identity (id text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS edge_identity (id text PRIMARY KEY);

CREATE TABLE IF NOT EXISTS node_versions (
  ver          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id           text NOT NULL REFERENCES node_identity(id),
  kind         text NOT NULL,
  body         text,
  uri          text,
  content_hash text,
  content_type text,
  props        text NOT NULL DEFAULT '{}',
  emb          vector(${dim}),
  valid_from   bigint NOT NULL,
  valid_to     bigint NOT NULL DEFAULT ${FOREVER_LIT},
  body_tsv     tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED
);
CREATE INDEX IF NOT EXISTS nv_asof ON node_versions(id, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS nv_kind ON node_versions(kind);
CREATE INDEX IF NOT EXISTS nodes_fts_gin ON node_versions USING gin(body_tsv);

CREATE TABLE IF NOT EXISTS edge_versions (
  ver        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id         text NOT NULL REFERENCES edge_identity(id),
  src        text NOT NULL REFERENCES node_identity(id),
  dst        text NOT NULL REFERENCES node_identity(id),
  rel        text NOT NULL,
  weight     real NOT NULL DEFAULT 1.0 CHECK (weight >= 0),
  props      text NOT NULL DEFAULT '{}',
  valid_from bigint NOT NULL,
  valid_to   bigint NOT NULL DEFAULT ${FOREVER_LIT}
);
CREATE INDEX IF NOT EXISTS ev_src_asof ON edge_versions(src, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS ev_dst_asof ON edge_versions(dst, valid_from, valid_to);

CREATE OR REPLACE VIEW nodes AS
  SELECT id, kind, body, uri, content_hash, content_type, props, emb
  FROM node_versions WHERE valid_to = ${FOREVER_LIT};
CREATE OR REPLACE VIEW edges AS
  SELECT id, src, dst, rel, weight, props
  FROM edge_versions WHERE valid_to = ${FOREVER_LIT};

CREATE TABLE IF NOT EXISTS archival_state (
  table_name text PRIMARY KEY, watermark bigint NOT NULL, updated_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS node_analytics (
  id          text PRIMARY KEY REFERENCES node_identity(id),
  pagerank    real,
  community   bigint,
  degree      bigint,
  computed_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS na_pagerank ON node_analytics(pagerank);
CREATE INDEX IF NOT EXISTS na_community ON node_analytics(community);
CREATE INDEX IF NOT EXISTS na_degree ON node_analytics(degree);
`;
}

function notYet(fragment: string): never {
	throw new Error(
		`dialect-sql: ${fragment}(postgres) not implemented yet — Postgres backend is a later phase`,
	);
}

/** The embedding column's type. libSQL: native `F32_BLOB(dim)`; Postgres: pgvector `vector(dim)`. */
export function embColumnType(dialect: Dialect, dim: number): string {
	if (dialect === 'postgres') notYet('embColumnType');
	return `F32_BLOB(${dim})`;
}

/**
 * Value expression for inserting a FRESH embedding bound as a JSON-array string (`[1,2,3]`).
 * libSQL parses it with `vector(?)`; pgvector casts the same text with `?::vector`.
 */
export function embFreshExpr(dialect: Dialect): string {
	return dialect === 'postgres' ? '?::vector' : 'vector(?)';
}

/**
 * Current-time ANN seed sub-SELECT (the body of `seeds AS ( … )`). Consumes 2 bound args:
 * the query embedding (JSON-array string) and k. libSQL uses the partial-live
 * `vector_top_k` index function joined by rowid; pgvector orders live rows by cosine
 * distance (`emb <=> $1::vector`). Both yield the top-k live node ids by ANN rank.
 */
export function annSeedsLive(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `
  SELECT id
  FROM node_versions
  WHERE valid_to = ${FOREVER_LIT} AND emb IS NOT NULL
  ORDER BY emb <=> ?::vector
  LIMIT ?`;
	}
	return `
  SELECT n.id AS id
  FROM vector_top_k('nv_emb_idx', vector(?), ?) v
  JOIN node_versions n ON n.rowid = v.id`;
}

/**
 * As-of-past ANN seed sub-SELECT (the body of `seeds AS ( … )`). Consumes 5 bound args:
 * embedding, over-fetch k, t, t, final k. Over-fetches live ANN candidates, keeps the
 * ids that have a version valid at :t, ranks them, truncates to k. libSQL ranks by the
 * index rowid proxy (`MIN(v.id)`); pgvector ranks by real cosine distance.
 */
export function annSeedsAsOf(dialect: Dialect): string {
	if (dialect === 'postgres') {
		return `
  SELECT live.id AS id, live.rk AS rk
  FROM (
    SELECT id, MIN(emb <=> ?::vector) AS rk
    FROM node_versions
    WHERE valid_to = ${FOREVER_LIT} AND emb IS NOT NULL
    GROUP BY id
    ORDER BY rk
    LIMIT ?
  ) live
  WHERE EXISTS (
    SELECT 1 FROM node_versions h
    WHERE h.id = live.id AND h.valid_from <= ? AND ? < h.valid_to
  )
  ORDER BY rk
  LIMIT ?`;
	}
	return `
  SELECT live.id AS id, live.rk AS rk
  FROM (
    SELECT n.id AS id, MIN(v.id) AS rk
    FROM vector_top_k('nv_emb_idx', vector(?), ?) v
    JOIN node_versions n ON n.rowid = v.id
    GROUP BY n.id
  ) live
  WHERE EXISTS (
    SELECT 1 FROM node_versions h
    WHERE h.id = live.id AND h.valid_from <= ? AND ? < h.valid_to
  )
  ORDER BY rk
  LIMIT ?`;
}

/**
 * Value expression for REBINDING an embedding read back from an existing row (carry-forward
 * on `updateNode`). libSQL rebinds the raw `F32_BLOB` bytes directly (`?`); pgvector reads
 * `emb` back as its text form `[1,2,3]`, so it re-casts with `?::vector`.
 */
export function embRebindExpr(dialect: Dialect): string {
	return dialect === 'postgres' ? '?::vector' : '?';
}

/**
 * The partial live ANN index DDL (D5) — partial over live rows (`valid_to = FOREVER`).
 * libSQL: `libsql_vector_idx` function-expression index. Postgres: a pgvector HNSW
 * index (`USING hnsw (emb vector_cosine_ops)`), added when the Postgres adapter lands.
 */
export function vectorIndexDDL(dialect: Dialect): string {
	if (dialect === 'postgres') notYet('vectorIndexDDL');
	return `CREATE INDEX IF NOT EXISTS nv_emb_idx ON node_versions(libsql_vector_idx(emb, 'metric=cosine')) WHERE valid_to = ${FOREVER_LIT};`;
}

/**
 * The full-text index object(s). libSQL: an external-content FTS5 virtual table over
 * `node_versions` (`content_rowid='ver'`). Postgres: a generated `tsvector` column +
 * GIN index (no virtual table), added when the Postgres adapter lands.
 */
export function ftsTableDDL(dialect: Dialect): string {
	if (dialect === 'postgres') notYet('ftsTableDDL');
	return `CREATE VIRTUAL TABLE IF NOT EXISTS nodes_fts USING fts5(body, content='node_versions', content_rowid='ver');`;
}

/**
 * The FTS sync trigger. libSQL external-content FTS5 does NOT auto-sync, so an
 * `AFTER INSERT` trigger mirrors every new `node_versions` row (rowid = `ver`) into
 * `nodes_fts`. Postgres needs no trigger (a generated `tsvector` column self-maintains),
 * so this becomes an empty string there when the adapter lands.
 */
export function ftsTriggerDDL(dialect: Dialect): string {
	if (dialect === 'postgres') notYet('ftsTriggerDDL');
	return `CREATE TRIGGER IF NOT EXISTS nodes_fts_ai AFTER INSERT ON node_versions BEGIN
  INSERT INTO nodes_fts(rowid, body) VALUES (new.ver, new.body);
END;`;
}
